# Generated by Django 4.2.6 on 2023-11-25 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_remove_user_basket_delete_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
