# Generated by Django 4.2.6 on 2023-11-21 14:34

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='', validators=[utils.validators.ImageFileExtensionValidator(), utils.validators.FileMaxSizeValidator()], verbose_name='Картинка'),
        ),
    ]
